### ISSUE TITLE
AttributeError: 'DrawObjectsEnv' object has no attribute '_seed'

### ISSUE THREAD

**Issue by ssen7** [agermanidis/gym-drawobjects#1]
We are using your environment for a reinforcement learning project. We tried to run the example.py file. Here is the error report:

```
WARNING:tensorflow:From c:\Users\Saurav\Documents\MSDS\Spring\SYS6582\Project\gym-drawobjects\gym_drawobjects\envs\drawobjects_env\inception.py:31: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2019-03-23 15:48:26.822389: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version
9. Use tf.nn.batch_normalization().
C:\Users\Saurav\Documents\Anaconda\lib\site-packages\gym\logger.py:30: UserWarning: ?[33mWARN: Environment '<class 'gym_drawobjects.envs.drawobjects_env.environment.DrawObjectsEnv'>' has deprecated methods '_step' and '_reset' rather than 'step' and 'reset'. Compatibility code invoked. Set _gym_disable_underscore_compat = True to disable this behavior.?[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "c:/Users/Saurav/Documents/MSDS/Spring/SYS6582/Project/gym-drawobjects/example.py", line 13, in <module>
    env = gym.make("drawobjects-v0")
  File "C:\Users\Saurav\Documents\Anaconda\lib\site-packages\gym\envs\registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Saurav\Documents\Anaconda\lib\site-packages\gym\envs\registration.py", line 129, in make
    patch_deprecated_methods(env)
  File "C:\Users\Saurav\Documents\Anaconda\lib\site-packages\gym\envs\registration.py", line 189, in patch_deprecated_methods
    env.seed  = env._seed
AttributeError: 'DrawObjectsEnv' object has no attribute '_seed'
```

I think there is an issue with the registering the new environment.

Any help here is appreciated.

**Comment by ssen7** [comment]
Whoops. Found the solution. Its the same issue as https://github.com/openai/gym/issues/860 .

Closing the issue.
